---
version: 2

registries:
  coop-ghcr:
    type: docker-registry
    url: ghcr.io
    username: CoopGithubServiceaccount
    password: ${{ secrets.DEPENDABOT_GHCR_PULL }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dd-trace-go-modules:
        patterns:
          - github.com/DataDog/dd-trace-go
          - github.com/DataDog/dd-trace-go/*
  - package-ecosystem: "docker"
    directory: "/docker-compose"
    registries:
      - coop-ghcr
    schedule:
      interval: "daily"
    groups:
      devtools:
        patterns:
          - coopnorge/engineering-docker-images/e0/*
