apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: go-datadog-lib
spec:
  description: "Light library package to wrap DataDog functionality"
  visibility: "public"


  branches:
    default: "main"
    protection:
      - id: "main"
        pattern: "main"
        requireSignedCommits: false
        requiredStatusChecks:
          checks:
            - "build"
            - "policy-bot: main"
            - "Supply Chain / Validate"
        requiredPullRequestReviews:
          requireCodeOwnerReviews: false

